version: '2'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - '5000:5000'
        volumes:
            - .:/code
        container_name: transactweb
    redis:
        image: 'redis:3.0-alpine'
        container_name: redisinstance
        command: redis-server
        ports:
            - '6379:6379'
    dbwriter:
        build:
            context: .
            dockerfile: Dockerfile.dbwriter
        volumes:
            - .:/code
        container_name: dbwriterinstance
